### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by SinYita** [Aatwitss/Python-Data-linear_regression#1]
你好，看了你的代码，感觉思路非常清晰，可否分享一下数据集，谢谢

**Comment by Aatwitss** [comment]
你好，感谢你的认可，请问需要哪一篇的数据集

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Weiyuan Du ***@***.***>
Sent: Thursday, April 18, 2024 5:14:54 AM
To: Aatwitss/Python-Data-linear_regression ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Aatwitss/Python-Data-linear_regression] 关于数据集 (Issue #1)


你好，看了你的代码，感觉思路非常清晰，可否分享一下数据集，谢谢

―

**Comment by SinYita** [comment]
感谢你的回复，房价预测这一个就可以了，谢谢你的帮助，祝你生活愉快

**Comment by Aatwitss** [comment]
你好，数据集如下：
[
[house_price.csv](https://github.com/Aatwitss/Python-Data-linear_regression/files/15051047/house_price.csv)
](url)

**Comment by SinYita** [comment]
谢谢你的数据集 祝生活愉快





------------------ Original ------------------
From: Aatwitss ***@***.***&gt;
Date: Sun, Apr 21, 2024 9:46 AM
To: Aatwitss/Python-Data-linear_regression ***@***.***&gt;
Cc: Weiyuan Du ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Aatwitss/Python-Data-linear_regression] 关于数据集 (Issue #1)





 
你好，数据集如下：
 [
 house_price.csv
 ](url)
